# Generated by Django 6.1.1 on 2026-09-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ratings', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('delivery_time', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('Slug', models.SlugField(max_length=100, unique=True)),
                ('instock', models.BooleanField(default=True)),
            ],
        ),
    ]
